/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenderRouteImport } from './routes/vender'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ScireRouteImport } from './routes/scire'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImovelIdRouteImport } from './routes/imovel.$id'

const VenderRoute = VenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ScireRoute = ScireRouteImport.update({
  id: '/scire',
  path: '/scire',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImovelIdRoute = ImovelIdRouteImport.update({
  id: '/imovel/$id',
  path: '/imovel/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/scire': typeof ScireRoute
  '/sobre': typeof SobreRoute
  '/vender': typeof VenderRoute
  '/imovel/$id': typeof ImovelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/scire': typeof ScireRoute
  '/sobre': typeof SobreRoute
  '/vender': typeof VenderRoute
  '/imovel/$id': typeof ImovelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/scire': typeof ScireRoute
  '/sobre': typeof SobreRoute
  '/vender': typeof VenderRoute
  '/imovel/$id': typeof ImovelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/imoveis'
    | '/scire'
    | '/sobre'
    | '/vender'
    | '/imovel/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/imoveis'
    | '/scire'
    | '/sobre'
    | '/vender'
    | '/imovel/$id'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/imoveis'
    | '/scire'
    | '/sobre'
    | '/vender'
    | '/imovel/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ImoveisRoute: typeof ImoveisRoute
  ScireRoute: typeof ScireRoute
  SobreRoute: typeof SobreRoute
  VenderRoute: typeof VenderRoute
  ImovelIdRoute: typeof ImovelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vender': {
      id: '/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof VenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scire': {
      id: '/scire'
      path: '/scire'
      fullPath: '/scire'
      preLoaderRoute: typeof ScireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imovel/$id': {
      id: '/imovel/$id'
      path: '/imovel/$id'
      fullPath: '/imovel/$id'
      preLoaderRoute: typeof ImovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ImoveisRoute: ImoveisRoute,
  ScireRoute: ScireRoute,
  SobreRoute: SobreRoute,
  VenderRoute: VenderRoute,
  ImovelIdRoute: ImovelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
